/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cs318_project;

/**
 *
 * @author peera
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnel_bg1 = new javax.swing.JPanel();
        pnel_bg2 = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 220, 201));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnel_bg1.setBackground(new java.awt.Color(249, 241, 224));
        pnel_bg1.setForeground(new java.awt.Color(249, 241, 224));

        pnel_bg2.setBackground(new java.awt.Color(255, 251, 241));

        lbl_name.setFont(new java.awt.Font("LilyUPC", 1, 36)); // NOI18N
        lbl_name.setText("Name");

        javax.swing.GroupLayout pnel_bg2Layout = new javax.swing.GroupLayout(pnel_bg2);
        pnel_bg2.setLayout(pnel_bg2Layout);
        pnel_bg2Layout.setHorizontalGroup(
            pnel_bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel_bg2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(lbl_name)
                .addContainerGap(694, Short.MAX_VALUE))
        );
        pnel_bg2Layout.setVerticalGroup(
            pnel_bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel_bg2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lbl_name)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnel_bg1Layout = new javax.swing.GroupLayout(pnel_bg1);
        pnel_bg1.setLayout(pnel_bg1Layout);
        pnel_bg1Layout.setHorizontalGroup(
            pnel_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel_bg1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pnel_bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        pnel_bg1Layout.setVerticalGroup(
            pnel_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel_bg1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pnel_bg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        getContentPane().add(pnel_bg1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_name;
    private javax.swing.JPanel pnel_bg1;
    private javax.swing.JPanel pnel_bg2;
    // End of variables declaration//GEN-END:variables
}
