/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cs318_project;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GradientPaint;
import java.awt.RenderingHints;
import javax.swing.JComponent;
import javax.swing.AbstractButton;
/**
 *
 * @author peera
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_right = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        btn_play = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        lbl_pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setFont(new java.awt.Font("LilyUPC", 0, 10)); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panel_right.setBackground(new java.awt.Color(254, 201, 160));

        lbl_title.setBackground(new java.awt.Color(130, 62, 10));
        lbl_title.setFont(new java.awt.Font("LilyUPC", 1, 66)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(130, 62, 10));
        lbl_title.setText("SNAKE GAME");

        btn_play.setFont(new java.awt.Font("IrisUPC", 1, 38)); // NOI18N
        btn_play.setText("Play");
        btn_play.setToolTipText("");
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });

        btn_Exit.setFont(new java.awt.Font("IrisUPC", 1, 38)); // NOI18N
        btn_Exit.setText("Exit");
        btn_Exit.setToolTipText("");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        lbl_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N

        javax.swing.GroupLayout panel_rightLayout = new javax.swing.GroupLayout(panel_right);
        panel_right.setLayout(panel_rightLayout);
        panel_rightLayout.setHorizontalGroup(
            panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rightLayout.createSequentialGroup()
                .addComponent(lbl_pic)
                .addGroup(panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_rightLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_rightLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_play, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        panel_rightLayout.setVerticalGroup(
            panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rightLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_play, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_rightLayout.createSequentialGroup()
                .addComponent(lbl_pic)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_play.setContentAreaFilled(false); // ปิดพื้นที่ปุ่มปกติ
        btn_play.setFocusPainted(false); // ปิดการแสดงผลโฟกัส
        btn_play.setBorderPainted(false); // ปิดการแสดงผลขอบ
        btn_play.setOpaque(false); // ทำให้ปุ่มโปร่งใสเพื่อให้การวาดเงาทำงาน
        btn_play.setForeground(Color.WHITE); // สีข้อความ
        btn_play.setFont(new Font("LilyUPC", Font.BOLD, 36)); // ตั้งฟอนต์

        // ปรับแต่ง UI สำหรับการวาดปุ่ม
        btn_play.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            private boolean isHovered = false; // ตัวแปรสำหรับตรวจจับ Hover

            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                int width = c.getWidth();
                int height = c.getHeight();

                // วาดเงาด้านหลังปุ่ม
                g2.setColor(new Color(255, 102, 0, 100)); // สีเงา (ส้มอ่อนโปร่งแสง)
                g2.fillRoundRect(5, 10, width - 10, height - 10, 30, 30);

                // วาดพื้นหลังปุ่ม (ไล่ระดับสี)
                GradientPaint gradientPaint = new GradientPaint(
                    0, 0,
                    isHovered ? new Color(255, 204, 0) : new Color(255, 153, 0), // สีเมื่อ Hover หรือปกติ
                    0, height,
                    isHovered ? new Color(255, 180, 0) : new Color(255, 102, 0)
                );
                g2.setPaint(gradientPaint);
                g2.fillRoundRect(0, 0, width - 10, height - 10, 30, 30);

                // วาดข้อความของปุ่ม
                super.paint(g, c);
                g2.dispose();
            }

            @Override
            protected void installListeners(final AbstractButton b) {
                super.installListeners(b);

                // เพิ่ม MouseListener เพื่อจัดการ Hover Effect
                b.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseEntered(java.awt.event.MouseEvent e) {
                        isHovered = true;
                        b.repaint();
                    }

                    @Override
                    public void mouseExited(java.awt.event.MouseEvent e) {
                        isHovered = false;
                        b.repaint();
                    }
                });
            }
        });
        btn_Exit.setContentAreaFilled(false); // ปิดพื้นที่ปุ่มปกติ
        btn_Exit.setFocusPainted(false); // ปิดการแสดงผลโฟกัส
        btn_Exit.setBorderPainted(false); // ปิดการแสดงผลขอบ
        btn_Exit.setOpaque(false); // ทำให้ปุ่มโปร่งใสเพื่อให้การวาดเงาทำงาน
        btn_Exit.setForeground(Color.WHITE); // สีข้อความ
        btn_Exit.setFont(new Font("LilyUPC", Font.BOLD, 36)); // ตั้งฟอนต์

        // ปรับแต่ง UI สำหรับการวาดปุ่ม
        btn_Exit.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            private boolean isHovered = false; // ตัวแปรสำหรับตรวจจับ Hover

            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                int width = c.getWidth();
                int height = c.getHeight();

                // วาดเงาด้านหลังปุ่ม
                g2.setColor(new Color(255, 102, 0, 100)); // สีเงา (ส้มอ่อนโปร่งแสง)
                g2.fillRoundRect(5, 10, width - 10, height - 10, 30, 30);

                // วาดพื้นหลังปุ่ม (ไล่ระดับสี)
                GradientPaint gradientPaint = new GradientPaint(
                    0, 0,
                    isHovered ? new Color(255, 204, 0) : new Color(255, 153, 0), // สีเมื่อ Hover หรือปกติ
                    0, height,
                    isHovered ? new Color(255, 180, 0) : new Color(255, 102, 0)
                );
                g2.setPaint(gradientPaint);
                g2.fillRoundRect(0, 0, width - 10, height - 10, 30, 30);

                // วาดข้อความของปุ่ม
                super.paint(g, c);
                g2.dispose();
            }

            @Override
            protected void installListeners(final AbstractButton b) {
                super.installListeners(b);

                // เพิ่ม MouseListener เพื่อจัดการ Hover Effect
                b.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseEntered(java.awt.event.MouseEvent e) {
                        isHovered = true;
                        b.repaint();
                    }

                    @Override
                    public void mouseExited(java.awt.event.MouseEvent e) {
                        isHovered = false;
                        b.repaint();
                    }
                });
            }
        });

        getContentPane().add(panel_right);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_play;
    private javax.swing.JLabel lbl_pic;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel panel_right;
    // End of variables declaration//GEN-END:variables
}
